---
title: "Programa de Prevención & Control del Dengue | 2024"
format: 
  dashboard:
      scrolling: true
      logo: https://www.gob.mx/cms/uploads/action_program/main_image/26942/post_post_portadavectores.gif
      nav-buttons: [twitter, github, facebook]
theme: custom.scss
---

```{r setup}
library(sf)
mapview::mapviewOptions(default = TRUE,
                        basemaps.color.shuffle = FALSE)
load("/Users/felipedzul/Library/CloudStorage/OneDrive-Personal/proyects/geocoding_mex/2024/8.RData/denmex_2024.RData")
library(magrittr)
```


# [**Cadenas de Transmisión**]{style="font-size:8pt"}

::: panel-tabset

### [**Monterrey**]{style="color:#990000"}

```{r}
denhotspots::transmission_chains_map(geocoded_dataset = z,
                                     cve_edo = "19",
                                     locality = c("Ciudad General Escobedo",
                                                  "Ciudad Apodaca",
                                                  "Guadalupe", "Monterrey", 
                                                  "Ciudad Santa Catarina",
                                                  "San Pedro Garza García", 
                                                  "Ciudad Benito Juárez",
                                                  "San Nicolás de los Garza"),
                                     dengue_cases = "Confirmado")
```

:::


# [**Mapas de Calor**]{style="font-size:8pt"}

::: panel-tabset

### [**Monterrey**]{style="color:#990000"}


:::


# [**Log Gaussian Cox Processes**]{style="font-size:8pt"}

::: panel-tabset

### [**Monterrey**]{style="color:#990000"}


:::
